---
  - hosts: cisco
    tasks:
      - name: Configure Login Banner
        ios_banner:
          banner: login
          state: present
          text: |
            # # # # # # # # # # # # # # # # # # # # # # # # #
            #   Unautorized access is strictly prohibited   #
            #                                               #
            # # # # # # # # # # # # # # # # # # # # # # # # #
